language: ruby
rvm:
  - 2.3.0
# Handle git submodules yourself
git:
  submodules: false
sudo: required
dist: trusty
before_install:
  - ./bin/travis/setup/git/submodules
  - ./bin/travis/setup/gosu/dependencies
  - gem install bundler -v 1.11.2
